#!/bin/bash

echo -e "                                                                                                               "
echo -e "                                                                                                               "
echo -e "     ██████╗ ██████╗ ███╗   ███╗██████╗  ██████╗ ███╗   ██╗███████╗███╗   ██╗████████╗    ██████╗ ██████╗      "
echo -e "    ██╔════╝██╔═══██╗████╗ ████║██╔══██╗██╔═══██╗████╗  ██║██╔════╝████╗  ██║╚══██╔══╝    ██╔══██╗██╔══██╗     "
echo -e "    ██║     ██║   ██║██╔████╔██║██████╔╝██║   ██║██╔██╗ ██║█████╗  ██╔██╗ ██║   ██║       ██║  ██║██████╔╝     "
echo -e "    ██║     ██║   ██║██║╚██╔╝██║██╔═══╝ ██║   ██║██║╚██╗██║██╔══╝  ██║╚██╗██║   ██║       ██║  ██║██╔══██╗     "
echo -e "    ╚██████╗╚██████╔╝██║ ╚═╝ ██║██║     ╚██████╔╝██║ ╚████║███████╗██║ ╚████║   ██║       ██████╔╝██████╔╝     "
echo -e "     ╚═════╝ ╚═════╝ ╚═╝     ╚═╝╚═╝      ╚═════╝ ╚═╝  ╚═══╝╚══════╝╚═╝  ╚═══╝   ╚═╝       ╚═════╝ ╚═════╝      "
echo -e "                                                                                                               "

db=./components
. ./functions

if [ ! -f "$db" ]; then
    echo "`basename $db` does not exist!"
    exit 1
fi

while true
do
    echo ""
    echo "      1) Add"
    echo "      2) View"
    echo "      3) Delete"
    echo "      4) Update"
    echo "      5) Search"
    echo -e "      0) Exit\n"

    read -p "       Choose an option: " opt
    echo -e "\n"
    case $opt in
    1) add ;;
    2) view_db ;;
    3) delete ;;
    4) update ;;
    5) search ;;
    0) echo "Bye-bye!"; exit 0 ;;
    *) echo "Invalid option!" ;;
    esac
done