#!/bin/bash


echo ""
echo "    ____  ______   ____             __          ____        __        __                  ";
echo "   / __ \\/ ____/  / __ \\____ ______/ /______   / __ \\____ _/ /_____ _/ /_  ____ _________ ";
echo "  / /_/ / /      / /_/ / __ \`/ ___/ __/ ___/  / / / / __ \`/ __/ __ \`/ __ \\/ __ \`/ ___/ _ \\";
echo " / ____/ /___   / ____/ /_/ / /  / /_(__  )  / /_/ / /_/ / /_/ /_/ / /_/ / /_/ (__  )  __/";
echo "/_/    \\____/  /_/    \\__,_/_/   \\__/____/  /_____/\\__,_/\\__/\\__,_/_.___/\\__,_/____/\\___/ ";
echo "                                                                                          ";
echo ""

db=./parts
. ./functions

if [ ! -f "$db" ]; then
    echo "`basename $db` does not exist!"
    echo "Creating `basename $db`..."
    echo "File created."
    touch $db
fi

while true
do
    echo ""
    echo "1) Add"
    echo "2) View"
    echo "3) Delete"
    echo "4) Update"
    echo "5) Search"
    echo "0) Exit"


    read -p "Choose an option: " opt
    case $opt in
    1) add ;;
    2) view_db ;;
    3) delete ;;
    4) update ;;
    5) search ;;
    0) exit 0 ;;
    *) echo "Invalid option!" ;;
    esac
done